import type { SmartPage, ThemeSettings } from "./types";
import { DEFAULT_WORKSPACE_ID } from "./workspaceConstants";
import { nowIso } from "./utils";

export const defaultTheme: ThemeSettings = {
  preset: "minimal-white",
  backgroundColor: "#ffffff",
  gradientFrom: "#ffffff",
  gradientTo: "#ffffff",
  backgroundImage: "",
  backgroundBlur: 0,
  textColor: "#404040",
  headingColor: "#000000",
  buttonBackground: "#000000",
  buttonTextColor: "#ffffff",
  buttonBorderColor: "transparent",
  buttonRadius: 12,
  buttonTransparency: 100,
  glassBlur: 0,
  shadow: 0,
  font: "inter",
  spacing: 8,
  profileLayout: "hero",
  profileAlignment: "left",
  surface: "plain",
  buttonStyle: "solid",
  buttonAnimation: false,
  backgroundStyle: "solid",
  showShareButton: false,
};

export function seedPages(): SmartPage[] {
  const timestamp = nowIso();

  return [
    {
      id: 1,
      workspaceId: DEFAULT_WORKSPACE_ID,
      name: "Dr. Moiz Khakiani",
      slug: "dr-moiz-khakiani",
      title: "Dr. Moiz Khakiani",
      bio: "Consultant, founder, and advisor. Book appointments, message the team, and find official links from one secure page.",
      profileImage:
        "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=600&q=80",
      logoImage: "",
      status: "published",
      theme: {
        ...defaultTheme,
        preset: "midnight",
        backgroundStyle: "gradient",
        surface: "glass-dark",
        headingColor: "#ffffff",
        gradientFrom: "#0f172a",
        gradientTo: "#0e7490",
        buttonBackground: "#f8fafc",
        buttonTextColor: "#0f172a",
        textColor: "#dbeafe",
      } as ThemeSettings,
      seo: {
        seoTitle: "Dr. Moiz Khakiani - Official Links",
        metaDescription: "Official contact and appointment links for Dr. Moiz Khakiani.",
        socialTitle: "Dr. Moiz Khakiani",
        socialDescription: "Appointments, WhatsApp, website, and official profiles.",
        ogImage: "",
        favicon: "",
      },
      integrations: { metaPixelId: "", gtmId: "" },
      views: 1240,
      uniqueVisitors: 884,
      createdAt: timestamp,
      updatedAt: timestamp,
      blocks: [
        {
          id: 101,
          pageId: 1,
          type: "whatsapp",
          title: "WhatsApp",
          subtitle: "Chat with the clinic team",
          url: "",
          icon: "whatsapp",
          phone: "+918850053273",
          message: "Hello, I would like more information.",
          imageUrl: "",
          videoUrl: "",
          settings: {},
          sortOrder: 1,
          isActive: true,
          clicks: 520,
          createdAt: timestamp,
          updatedAt: timestamp,
        },
        {
          id: 102,
          pageId: 1,
          type: "website",
          title: "Official Website",
          subtitle: "Services, timings, and contact details",
          url: "https://example.com",
          icon: "website",
          phone: "",
          message: "",
          imageUrl: "",
          videoUrl: "",
          settings: {},
          sortOrder: 2,
          isActive: true,
          clicks: 244,
          createdAt: timestamp,
          updatedAt: timestamp,
        },
        {
          id: 103,
          pageId: 1,
          type: "email",
          title: "Email",
          subtitle: "Send a detailed inquiry",
          url: "hello@example.com",
          icon: "email",
          phone: "",
          message: "Hello, I would like to connect.",
          imageUrl: "",
          videoUrl: "",
          settings: {},
          sortOrder: 3,
          isActive: true,
          clicks: 120,
          createdAt: timestamp,
          updatedAt: timestamp,
        },
        {
          id: 104,
          pageId: 1,
          type: "video",
          title: "Signup walkthrough",
          subtitle: "Watch the guide directly on this page",
          url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          icon: "video",
          phone: "",
          message: "",
          imageUrl: "",
          videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          settings: {},
          sortOrder: 4,
          isActive: true,
          clicks: 0,
          createdAt: timestamp,
          updatedAt: timestamp,
        },
      ],
    },
    {
      id: 2,
      workspaceId: DEFAULT_WORKSPACE_ID,
      name: "MIK Solutions",
      slug: "mik",
      title: "MIK Solutions",
      bio: "Business links, support contacts, social profiles, and campaign pages in one polished hub.",
      profileImage:
        "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=600&q=80",
      logoImage: "",
      status: "published",
      theme: {
        ...defaultTheme,
        preset: "purple-glass",
        backgroundStyle: "gradient",
        surface: "glass-dark",
        headingColor: "#ffffff",
        gradientFrom: "#581c87",
        gradientTo: "#1d4ed8",
        buttonBackground: "#ffffff",
        buttonTextColor: "#1e1b4b",
      },
      seo: {
        seoTitle: "MIK Solutions - Smart Contact Page",
        metaDescription: "Official public links and contact options for MIK Solutions.",
        socialTitle: "MIK Solutions",
        socialDescription: "Contact, social links, and official resources.",
        ogImage: "",
        favicon: "",
      },
      integrations: { metaPixelId: "", gtmId: "" },
      views: 820,
      uniqueVisitors: 603,
      createdAt: timestamp,
      updatedAt: timestamp,
      blocks: [
        {
          id: 201,
          pageId: 2,
          type: "telegram",
          title: "Telegram",
          subtitle: "Join our updates channel",
          url: "miksolutions",
          icon: "telegram",
          phone: "",
          message: "",
          imageUrl: "",
          videoUrl: "",
          settings: {},
          sortOrder: 1,
          isActive: true,
          clicks: 214,
          createdAt: timestamp,
          updatedAt: timestamp,
        },
      ],
    },
  ];
}
